### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by yosimitsu13** [FlowSoft87/MCExport#3]
I looked at your MCExport project and it really is an incredible idea. I am a 3d modeling and animation student, I want to create a mod, and I would like if you could help me create it since it is convenient for me to be able to animate the models in blender and export them to minecraft, I OFFER YOU 100 DOLLARS A MORE IF YOU CHEER UP, I must clarify that it will not be a single payment because the mod that I plan to do is large and I will need your services for each update, so I await your response.

**Comment by FlowSoft87** [comment]
Dear yosimitsu13,

I am glad you like the project!
From your message I understand that you would like me to improve the exporter to export model animations.

The nature of the project has always been that of a hobby and this is not likely to change due to time limitations.
However, I am happy to help when it is possible within my constraints.

The following are my thoughts on the implementation of this feature:
Blender allows to define animations by setting values at fixed frames and defining transformations (linear and others) to interpolate the values between those frames.
As far as I recall, Minecraft handles animations inside the model classes by adjusting model-block positions/sizes based on a tick (1/20th of a second) and a fractional tick whose value depends on the actual framerate.
Thus, it is necessary to port this frame interpolation scheme over to the Minecraft model in some way.
Also, one typically uses multiple different animations in different situations (standing, running, ...) and it is necessary to interpolate between them fluently.
Furthermore, Minecraft animations do not happen on the client-side only: the Entity itself needs to include information about the state of its animation (which animation, when did the entity enter the animation, ...).

Maybe you can tell me what the mod is about and how exactly you want to use the exported models?

Best regards,
FlowSoft87
